
run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 15

linters:
    enable:
        - misspell
        - gofmt
        - golint
        - goimports
    disable:
        - errcheck
        - gas
        - megacheck
        - varcheck
        - gochecknoglobals
        # Disabled due to: ":0: nilness: impossible condition: non-nil == nil (govet)"
        - govet
    fast: false
